---
:shared:
  :page_feedbacks:
    - id
    - useful
    - feedback
    - url
    - created_at
    - updated_at
  :feedbacks:
    - id
    - rating
    - url
    - description
    - email
    - topic
    - can_contact
    - created_at
    - updated_at

