---
:shared:
  :page_feedbacks:
    - id
    - useful
    - feedback
    - url
    - created_at
    - updated_at
  :feedbacks:
    - id
    - rating
    - url
    - description
    - email
    - topic
    - can_contact
    - created_at
    - updated_at
  :users:
    - id
    - first_name
    - last_name
    - email_address
    - one_login_sign_in_uid
    - last_signed_in_at
    - trn
    - date_of_birth
    - created_at
    - updated_at
