---
:shared:
  :page_feedbacks:
    - id
    - useful
    - feedback
    - url
    - created_at
    - updated_at
  :feedbacks:
    - id
    - rating
    - url
    - description
    - email
    - topic
    - can_contact
    - created_at
    - updated_at
  :support_requests:
    - name
    - id
    - email
    - area_of_website
    - area_of_website_url
    - problem
    - updated_at
    - created_at
