name: Set maintenance mode (Centralized)

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
          - staging
          - production
      mode:
        required: true
        type: choice
        options:
          - enable
          - disable

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  set-maintenance-mode:
    name: Set maintenance mode (centralized)
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable or disable maintenance mode
        uses: DFE-Digital/github-actions/maintenance-v2@2392-spike-centralise-maintenance-page
        with:
          # Azure authentication
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          
          # Core configuration
          environment: ${{ inputs.environment }}
          mode: ${{ inputs.mode }}
          docker-repository: ghcr.io/dfe-digital/teacher-success-maintenance
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
          # Config file with maintenance settings
          config-file: maint-config.txt
          
          # Use spike branch for templates (will use main once merged)
          template-ref: "2392-spike-centralise-maintenance-page"